
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Dec 16 11:05:25 CST 2009
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int STRING_LITERAL = 49;
  public static final int GTEQ = 38;
  public static final int MULT = 10;
  public static final int CHAR = 4;
  public static final int LTEQ = 37;
  public static final int LPAREN = 15;
  public static final int INT = 3;
  public static final int MINUS = 31;
  public static final int RPAREN = 16;
  public static final int BOOLEAN_LITERAL = 47;
  public static final int OROR = 42;
  public static final int CHARACTER_LITERAL = 48;
  public static final int NOT = 32;
  public static final int SEMICOLON = 9;
  public static final int LT = 35;
  public static final int ILLEGAL_CHARACTER = 44;
  public static final int COMMA = 11;
  public static final int CLASS = 19;
  public static final int ANDAND = 41;
  public static final int DIV = 33;
  public static final int PLUS = 30;
  public static final int NULL_LITERAL = 51;
  public static final int IF = 25;
  public static final int THIS = 22;
  public static final int DOT = 8;
  public static final int EOF = 0;
  public static final int BOOLEAN = 2;
  public static final int RETURN = 28;
  public static final int SUPER = 23;
  public static final int NEW = 29;
  public static final int error = 1;
  public static final int EQEQ = 39;
  public static final int MOD = 34;
  public static final int VOID = 21;
  public static final int EQ = 14;
  public static final int LBRACK = 6;
  public static final int COLON = 17;
  public static final int FLOATING_POINT_LITERAL = 46;
  public static final int LBRACE = 12;
  public static final int ELSE = 26;
  public static final int RBRACK = 7;
  public static final int WHILE = 27;
  public static final int FLOAT = 5;
  public static final int PUBLIC = 18;
  public static final int RBRACE = 13;
  public static final int EXTENDS = 20;
  public static final int QUESTION = 43;
  public static final int AT = 24;
  public static final int GT = 36;
  public static final int NOTEQ = 40;
  public static final int IDENTIFIER = 50;
  public static final int INTEGER_LITERAL = 45;
}

